import {Component, Input, OnInit} from '@angular/core';

import {BreakpointObserver, Breakpoints} from '@angular/cdk/layout';
import {OnDestroy} from '@angular/core';
import {Subject} from 'rxjs';
import {map, takeUntil} from 'rxjs/operators';
import {MatDialog} from "@angular/material/dialog";
import {AngularFireDatabase} from "@angular/fire/compat/database";
import {Title} from "@angular/platform-browser";
import { Meta } from '@angular/platform-browser';
import {JobDescriptionComponent} from "./job-description/job-description.component";
import {ActivatedRoute, Router} from "@angular/router";


export interface JobListing {
  id: number;
  listingTitle: string;
  jobTitle: string;
  appDeadline: string;
  description: string;
  employer: string;
  duration: string;
  format: string;
  qualifications: any;
  index: number;
  w_Visible: boolean;
  wHours: string;
  wStatus: string;
  tasks: string;
  keys: [];
  w_Image: string;
  renumeration: string;
}
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  id: any;
  index = '20220415';
  jobTitle: any;
  positionIndex: string = '';
  keyArray = [];
  destroyed = new Subject<void>();
  currentScreenSize: string | undefined;
  finApplicationId = '';

  openPositions: Array <any> = [
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},





    {listingTitle: '',
      jobTitle: '',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular Biology/Molecular Genetics (priority) or Chemistry/Physics',
        'Basic programming and statistics skills',
        'Good writing/reporting skills',
        'High level of English proficiency',
        'Ability to learn quickly, easily read and comprehend scientific literature, motivation to learn bioinformatics',
        'Good communication skills',
        'Responsibility and time management'],
      w_Image: ''},
    {listingTitle: 'Systems biology analysis of liver metastases',
      jobTitle: 'Bioinformatics Researcher',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular/Cancer Biology and Genomics',
        'Ability to read and comprehend scientific papers, extract data',
        'Experience with spreadsheet editors',
        'Beginner/intermediate programming skills in R (preferable) or Python',
        'Desired familiarity with genomic databases (NCBI, UCSC,GEO)']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']}
  ];
  openInternships: Array <any> = [
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: {},
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: ''},





    {listingTitle: '',
      jobTitle: '',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular Biology/Molecular Genetics (priority) or Chemistry/Physics',
        'Basic programming and statistics skills',
        'Good writing/reporting skills',
        'High level of English proficiency',
        'Ability to learn quickly, easily read and comprehend scientific literature, motivation to learn bioinformatics',
        'Good communication skills',
        'Responsibility and time management'],
      w_Image: ''},
    {listingTitle: 'Systems biology analysis of liver metastases',
      jobTitle: 'Bioinformatics Researcher',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular/Cancer Biology and Genomics',
        'Ability to read and comprehend scientific papers, extract data',
        'Experience with spreadsheet editors',
        'Beginner/intermediate programming skills in R (preferable) or Python',
        'Desired familiarity with genomic databases (NCBI, UCSC,GEO)']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']}
  ];
  reversedArr = [];
  displayNameMap = new Map([
    [Breakpoints.XSmall, 'XSmall'],
    [Breakpoints.Small, 'Small'],
    [Breakpoints.Medium, 'Medium'],
    [Breakpoints.Large, 'Large'],
    [Breakpoints.XLarge, 'XLarge'],
  ]);
  omicss2022: Array <any> = [{}];
  constructor(breakpointObserver: BreakpointObserver,
              public dialog: MatDialog,
              private db: AngularFireDatabase,
              private titleService: Title,
              private metaTagService: Meta,
              private route: ActivatedRoute,
              private router: Router) {
    breakpointObserver
      .observe([
        Breakpoints.XSmall,
        Breakpoints.Small,
        Breakpoints.Medium,
        Breakpoints.Large,
        Breakpoints.XLarge,
      ])
      .pipe(takeUntil(this.destroyed))
      .subscribe(result => {
        for (const query of Object.keys(result.breakpoints)) {
          if (result.breakpoints[query]) {
            this.currentScreenSize = this.displayNameMap.get(query) ?? 'Unknown';
          }
        }
      });
  }

  public setTitle(newTitle: string) {
    this.titleService.setTitle(newTitle);
  }

  ngOnInit(){
    this.metaTagService.addTags([
      { name: 'keywords', content: 'Armenian Bioinformatics Institute, Job Application Portal' },
      { name: 'robots', content: 'index, follow' },
      { name: 'author', content: 'Armenian Bioinformatics Institute' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { name: 'date', content: '2022-02-07', scheme: 'YYYY-MM-DD' },
      { charset: 'UTF-8' }
    ]);
    this.metaTagService.updateTag({property: 'og:image', content: 'https://abi.am/wp-content/uploads/2021/10/cropped-ABI_logo_final-01-1-scaled-1.jpg'});
    this.setTitle('ABI Application Portal');
    this.db.list('Applications').snapshotChanges().subscribe(res => {
      for (let i=0; i<res.length; i++){
        // @ts-ignore
        this.keyArray.push(res[i].key);
      }
      this.keyArray.reverse();
      this.db.list('Applications').valueChanges().subscribe(res=>{
        for(let i = 0; i<res.length; i++){
          // @ts-ignore
          if(this.keyArray[i].includes('_')){
            // @ts-ignore
            this.db.list('Applications/' + this.keyArray[i].toString()).valueChanges()
              .subscribe((val: Array<any>)=> {
                // @ts-ignore
                this.openInternships[i].appDeadline = val[0].toString();
                // @ts-ignore
                this.openInternships[i].duration = val[1].toString();
                // @ts-ignore
                this.openInternships[i].employer = val[2].toString();
                // @ts-ignore
                this.openInternships[i].format = val[3].toString();
                // @ts-ignore
                this.openInternships[i].jobTitle = val[4];
                // @ts-ignore
                this.openInternships[i].listingTitle = val[5];
                // @ts-ignore
                this.openInternships[i].qualifications = val[6];
                // @ts-ignore
                this.openInternships[i].w_Image = val[8];
                // @ts-ignore
                this.openInternships[i].w_Visible = val[9];
                // @ts-ignore
                this.openInternships[i].wHours = val[7];
                // @ts-ignore
                this.openInternships[i].description = val[10];
                // @ts-ignore
                this.openInternships[i].wStatus = val[11];
                // @ts-ignore
                this.openInternships[i].tasks = val[12];
                // @ts-ignore
                this.openInternships[i].renumeration = val[13];
              });
          } else {
            // @ts-ignore
            this.db.list('Applications/' + this.keyArray[i].toString()).valueChanges()
              .subscribe((val: Array<any>)=> {
                // @ts-ignore
                this.openPositions[i].appDeadline = val[0].toString();
                // @ts-ignore
                this.openPositions[i].duration = val[1].toString();
                // @ts-ignore
                this.openPositions[i].employer = val[2].toString();
                // @ts-ignore
                this.openPositions[i].format = val[3].toString();
                // @ts-ignore
                this.openPositions[i].jobTitle = val[4];
                // @ts-ignore
                this.openPositions[i].listingTitle = val[5];
                // @ts-ignore
                this.openPositions[i].qualifications = val[6];
                // @ts-ignore
                this.openPositions[i].w_Image = val[8];
                // @ts-ignore
                this.openPositions[i].w_Visible = val[9];
                // @ts-ignore
                this.openPositions[i].wHours = val[7];
                // @ts-ignore
                this.openPositions[i].description = val[10];
                // @ts-ignore
                this.openPositions[i].wStatus = val[11];
                // @ts-ignore
                this.openPositions[i].tasks = val[12];
                // @ts-ignore
                this.openPositions[i].renumeration = val[13];
              });
          }

        }
        // this.openPositions = this.openPositions.slice().reverse();
      });
    });



  }

  openDialog(index:number): void{
    this.positionIndex = this.keyArray[index];
    console.log(this.reversedArr);
    let idx = index;
    this.id = this.keyArray[index];
    let taskArr: any[] = [];
    // @ts-ignore
    if(this.keyArray[index].includes('_')){
      this.finApplicationId = this.id.substring(this.id.length-7);
      this.finApplicationId = this.finApplicationId.slice(0,4);
      this.jobTitle = this.openInternships[index].jobTitle.toLowerCase().replace(/\s+/g, '-');
      this.jobTitle = this.jobTitle.replace(/\//g, '-');
      const temp = this.openInternships[idx].qualifications;
      if(this.openInternships[idx].tasks !=''){
        const tasks = this.openInternships[idx].tasks;
        // @ts-ignore
        Object.keys(tasks).map(index => {
          //@ts-ignore
          taskArr.push(tasks[index]);
          return taskArr;
        })
      }

      let arr: any[] = [];
      Object.keys(temp).map(index => {
        //@ts-ignore
        arr.push(temp[index]);
        return arr;
      });
    }
    else {
      this.finApplicationId = this.id.substring(this.id.length-6);
      this.finApplicationId = this.finApplicationId.slice(0,4);
      this.jobTitle = this.openPositions[index].jobTitle.toLowerCase().replace(/\s+/g, '-');
      this.jobTitle = this.jobTitle.replace(/\//g, '-');
      const temp = this.openPositions[idx].qualifications;
      if(this.openPositions[idx].tasks !=''){
        const tasks = this.openPositions[idx].tasks;
        // @ts-ignore
        Object.keys(tasks).map(index => {
          //@ts-ignore
          taskArr.push(tasks[index]);
          return taskArr;
        })
      }

      let arr: any[] = [];
      Object.keys(temp).map(index => {
        //@ts-ignore
        arr.push(temp[index]);
        return arr;
      });
    }

     this.router.navigate([this.jobTitle + '-' + this.finApplicationId]);
  }
  ngOnDestroy() {
    this.destroyed.next();
    this.destroyed.complete();
  }


}
